# -- TEST environment overrides --

namespace: reports-scheduler-test

image:
  registry: artifactory.example.com
  repository: docker-local/reports-scheduler

config:
  SPRING_PROFILES_ACTIVE: test
  LOG_LEVEL: INFO

reportsJob:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  javaOpts: "-Xms256m -Xmx512m"

deleteJob:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  javaOpts: "-Xms128m -Xmx256m"
